# Generated by Django 5.2.16 on 2026-07-29 01:55

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('archived', 'Arquivado')], default='active', max_length=20)),
                ('default_unit', models.CharField(default='un', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('archived', 'Arquivado')], default='active', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ('name', 'sku'),
            },
        ),
        migrations.CreateModel(
            name='ProductIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('sku', 'SKU alternativo'), ('ean', 'EAN'), ('gtin', 'GTIN'), ('internal_code', 'Código interno'), ('supplier_code', 'Código de fornecedor'), ('other', 'Outro')], max_length=30)),
                ('value', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_identifiers', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='products.productvariant')),
            ],
            options={
                'ordering': ('kind', 'value'),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'status', 'name'], name='product_org_status_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive', 'archived'))), name='product_status_valid'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['organization', 'sku'], name='product_variant_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['organization', 'barcode'], name='product_variant_barcode_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('sku'), condition=models.Q(('sku__gt', '')), name='product_variant_sku_unique_org'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__gt', '')), fields=('organization', 'barcode'), name='product_variant_barcode_unique_org'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive', 'archived'))), name='product_variant_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='productidentifier',
            constraint=models.UniqueConstraint(models.F('organization'), models.F('kind'), django.db.models.functions.text.Lower('value'), name='product_identifier_unique_org'),
        ),
        migrations.AddConstraint(
            model_name='productidentifier',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('sku', 'ean', 'gtin', 'internal_code', 'supplier_code', 'other'))), name='product_identifier_kind_valid'),
        ),
    ]
