MESSAGE_CREATED = "messaging.message_created"
MESSAGE_STATUS_CHANGED = "messaging.message_status_changed"

SOURCE_EVENT_ORDER_CONFIRMED = "order.confirmed"
SOURCE_EVENT_FULFILLMENT_READY = "fulfillment.ready"
SOURCE_EVENT_FULFILLMENT_DISPATCHED = "fulfillment.dispatched"
SOURCE_EVENT_FULFILLMENT_COMPLETED = "fulfillment.completed"
SOURCE_EVENT_PAYMENT_CHECKOUT_ACTIVATED = "payment.checkout_activated"
SOURCE_EVENT_PAYMENT_STATUS_CHANGED = "payment.status_changed"

ALLOWLISTED_SOURCE_EVENTS = frozenset(
    {
        SOURCE_EVENT_ORDER_CONFIRMED,
        SOURCE_EVENT_FULFILLMENT_READY,
        SOURCE_EVENT_FULFILLMENT_DISPATCHED,
        SOURCE_EVENT_FULFILLMENT_COMPLETED,
        SOURCE_EVENT_PAYMENT_CHECKOUT_ACTIVATED,
        SOURCE_EVENT_PAYMENT_STATUS_CHANGED,
    }
)

SOURCE_EVENT_CONTRACT_VERSIONS = {
    SOURCE_EVENT_ORDER_CONFIRMED: 1,
    SOURCE_EVENT_FULFILLMENT_READY: 1,
    SOURCE_EVENT_FULFILLMENT_DISPATCHED: 1,
    SOURCE_EVENT_FULFILLMENT_COMPLETED: 1,
    SOURCE_EVENT_PAYMENT_CHECKOUT_ACTIVATED: 1,
    SOURCE_EVENT_PAYMENT_STATUS_CHANGED: 1,
}
