# Generated by Django 5.2.16 on 2026-07-30 02:12

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('channel', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('surcharge_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('customer_document_snapshot', models.CharField(blank=True, max_length=14)),
                ('customer_contact_snapshot', models.JSONField(blank=True, default=dict)),
                ('shipping_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('billing_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('snapshot_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderCommandReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('result_item_id', models.UUIDField(blank=True, null=True)),
                ('resulting_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_command_receipts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_command_receipts', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('name_snapshot', models.CharField(max_length=200)),
                ('variant_snapshot', models.CharField(blank=True, max_length=200)),
                ('sku_snapshot', models.CharField(blank=True, max_length=64)),
                ('unit_snapshot', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('surcharge_reason', models.CharField(blank=True, max_length=500)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariant')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_number_sequence', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], max_length=20)),
                ('command_id', models.CharField(max_length=64)),
                ('reason_provided', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_status_history', to='organizations.organization')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='order_org_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'customer', 'created_at'], name='order_org_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='order_number_unique_per_org'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'confirmed', 'cancelled'))), name='order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'BRL')), name='order_currency_brl'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='order_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_total__gte', 0)), name='order_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('surcharge_total__gte', 0)), name='order_surcharge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_total__lte', models.F('subtotal'))), name='order_discount_not_above_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('discount_total')), '+', models.F('surcharge_total')))), name='order_total_formula'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancel_reason', ''), ('cancelled_at__isnull', True), ('confirmed_at__isnull', True), ('status', 'draft')), models.Q(('cancel_reason', ''), ('cancelled_at__isnull', True), ('confirmed_at__isnull', False), ('status', 'confirmed')), models.Q(('cancelled_at__isnull', False), ('status', 'cancelled'), models.Q(('cancel_reason', ''), _negated=True)), _connector='OR'), name='order_status_metadata_consistent'),
        ),
        migrations.AddIndex(
            model_name='ordercommandreceipt',
            index=models.Index(fields=['organization', 'order'], name='order_receipt_org_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordercommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'operation', 'idempotency_key'), name='order_command_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['organization', 'order'], name='order_item_org_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'position'), name='order_item_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='order_item_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_item_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('gross_total__gte', 0)), name='order_item_gross_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='order_item_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('surcharge_amount__gte', 0)), name='order_item_surcharge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_item_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('gross_total'))), name='order_item_discount_not_above_gross'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross_total'), '-', models.F('discount_amount')), '+', models.F('surcharge_amount')))), name='order_item_total_formula'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('variant__isnull', True), ('product__isnull', False), _connector='OR'), name='order_item_variant_requires_product'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('surcharge_amount', 0), ('surcharge_reason', '')), models.Q(('surcharge_amount__gt', 0), models.Q(('surcharge_reason', ''), _negated=True)), _connector='OR'), name='order_item_surcharge_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='ordernumbersequence',
            constraint=models.CheckConstraint(condition=models.Q(('next_number__gte', 1)), name='order_sequence_positive'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['organization', 'order', 'created_at'], name='order_history_org_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderstatushistory',
            constraint=models.UniqueConstraint(fields=('order', 'to_status'), name='order_history_status_unique'),
        ),
        migrations.AddConstraint(
            model_name='orderstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status__in', ('', 'draft', 'confirmed', 'cancelled'))), name='order_history_from_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='orderstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ('draft', 'confirmed', 'cancelled'))), name='order_history_to_status_valid'),
        ),
    ]
