# Generated by Django 5.2.16 on 2026-07-29 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_type', models.CharField(choices=[('individual', 'Pessoa física'), ('company', 'Pessoa jurídica')], max_length=20)),
                ('display_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('document_normalized', models.CharField(blank=True, max_length=14)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('blocked', 'Bloqueado')], default='active', max_length=20)),
                ('notes_summary', models.CharField(blank=True, max_length=500)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_sources', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organizations.organization')),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('phone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('normalized_value', models.CharField(max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='customers.customer')),
            ],
            options={
                'ordering': ('kind', '-is_primary', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=60)),
                ('country', models.CharField(default='BR', max_length=2)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='customers.customer')),
            ],
            options={
                'ordering': ('-is_default_shipping', 'label', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CustomerMerge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=500)),
                ('rules_applied', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_merges', to='organizations.organization')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_merges_performed', to=settings.AUTH_USER_MODEL)),
                ('source_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merges_as_source', to='customers.customer')),
                ('target_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merges_as_target', to='customers.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_notes', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'status', 'display_name'], name='customer_org_status_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('document_normalized__gt', '')), fields=('organization', 'document_normalized'), name='customer_document_unique_per_org'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('customer_type__in', ('individual', 'company'))), name='customer_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive', 'blocked'))), name='customer_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('merged_into_id')), _negated=True), name='customer_cannot_merge_into_self'),
        ),
        migrations.AddIndex(
            model_name='contactpoint',
            index=models.Index(fields=['customer', 'kind', 'normalized_value'], name='customer_contact_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('customer', 'kind'), name='customer_contact_one_active_primary'),
        ),
        migrations.AddConstraint(
            model_name='contactpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'kind', 'normalized_value'), name='customer_contact_active_value_unique'),
        ),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default_shipping', True)), fields=('customer',), name='customer_address_one_shipping_default'),
        ),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default_billing', True)), fields=('customer',), name='customer_address_one_billing_default'),
        ),
        migrations.AddConstraint(
            model_name='customermerge',
            constraint=models.UniqueConstraint(fields=('source_customer',), name='customer_merge_source_once'),
        ),
        migrations.AddConstraint(
            model_name='customermerge',
            constraint=models.CheckConstraint(condition=models.Q(('source_customer', models.F('target_customer')), _negated=True), name='customer_merge_distinct_customers'),
        ),
    ]
