# Generated by Django 5.2.16 on 2026-08-13 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semantic_key', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=20)),
                ('locale', models.CharField(default='pt-BR', max_length=20)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('parameter_schema', models.JSONField(blank=True, default=list)),
                ('provider_template_reference', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ('semantic_key', 'version'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('order', 'Pedido'), ('fulfillment', 'Fulfillment'), ('payment', 'Pagamento')], max_length=20)),
                ('source_id', models.UUIDField()),
                ('source_version', models.PositiveBigIntegerField()),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=80)),
                ('template_semantic_key', models.CharField(max_length=120)),
                ('template_version', models.PositiveBigIntegerField()),
                ('channel_kind', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=20)),
                ('locale', models.CharField(max_length=20)),
                ('customer_display_name', models.CharField(max_length=200)),
                ('destination_snapshot', models.CharField(max_length=200)),
                ('permission_evidence_id', models.UUIDField(blank=True, null=True)),
                ('permission_policy_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('parameter_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('queued', 'Na fila'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('uncertain', 'Incerto')], default='pending', max_length=20)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('contact_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='customers.contactpoint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='organizations.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='messaging.messagetemplate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessagingChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=20)),
                ('display_name', models.CharField(max_length=120)),
                ('external_channel_id', models.CharField(blank=True, max_length=200)),
                ('credential_alias', models.CharField(blank=True, max_length=120)),
                ('capability_snapshot', models.JSONField(blank=True, default=list)),
                ('state', models.CharField(choices=[('inactive', 'Inativo'), ('connecting', 'Conectando'), ('pairing_required', 'Aguardando pareamento'), ('active', 'Ativo'), ('degraded', 'Degradado'), ('disconnected', 'Desconectado'), ('disabled', 'Desabilitado')], default='inactive', max_length=30)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messaging_channels', to='organizations.organization')),
            ],
            options={
                'ordering': ('kind', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='MessageDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('sending', 'Enviando'), ('accepted', 'Aceito'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('uncertain', 'Incerto')], default='requested', max_length=20)),
                ('dispatch_key', models.CharField(max_length=64)),
                ('provider_correlation_tag', models.CharField(max_length=160)),
                ('external_message_id', models.CharField(blank=True, max_length=200)),
                ('dispatch_lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('dispatch_lease_expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('dispatch_attempts', models.PositiveIntegerField(default=0, editable=False)),
                ('dispatch_available_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('dispatch_error_code', models.CharField(blank=True, editable=False, max_length=40)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='messaging.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_delivery_attempts', to='organizations.organization')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_attempts', to='messaging.messagingchannel')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageAutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=120)),
                ('event_version', models.PositiveBigIntegerField(default=1)),
                ('purpose', models.CharField(max_length=80)),
                ('is_enabled', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_automation_rules', to='organizations.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to='messaging.messagetemplate')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to='messaging.messagingchannel')),
            ],
            options={
                'ordering': ('event_type', 'purpose'),
            },
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='messaging.messagingchannel'),
        ),
        migrations.CreateModel(
            name='MessagingPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=20)),
                ('purpose', models.CharField(max_length=80)),
                ('decision', models.CharField(choices=[('allowed', 'Permitido'), ('suppressed', 'Suprimido')], max_length=20)),
                ('provenance', models.CharField(max_length=120)),
                ('policy_version', models.PositiveBigIntegerField(default=1)),
                ('effective_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('contact_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messaging_preferences', to='customers.contactpoint')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messaging_preferences', to='organizations.organization')),
            ],
            options={
                'ordering': ('-effective_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MessagingProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('evolution', 'Evolution API (linked device)'), ('whatsapp_cloud', 'WhatsApp Business Platform Cloud API'), ('ses', 'Amazon SES')], max_length=30)),
                ('mode', models.CharField(choices=[('linked_device', 'Dispositivo vinculado (não oficial)'), ('official', 'API oficial Meta'), ('email', 'E-mail transacional')], max_length=30)),
                ('display_name', models.CharField(max_length=120)),
                ('credential_alias', models.CharField(max_length=120)),
                ('webhook_secret_alias', models.CharField(blank=True, max_length=120)),
                ('capability_snapshot', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('callbacks_enabled', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messaging_provider_connections', to='organizations.organization')),
            ],
            options={
                'ordering': ('provider', 'display_name'),
            },
        ),
        migrations.AddField(
            model_name='messagingchannel',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='messaging.messagingproviderconnection'),
        ),
        migrations.CreateModel(
            name='MessageWebhookReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_event_id', models.CharField(max_length=200)),
                ('external_message_id', models.CharField(max_length=200)),
                ('authenticated_request_id_digest', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('canonical_result', models.CharField(max_length=30)),
                ('has_inconsistency', models.BooleanField(default=False)),
                ('reason_code', models.CharField(blank=True, max_length=60)),
                ('accepted', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_webhook_receipts', to='organizations.organization')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_receipts', to='messaging.messagingchannel')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_receipts', to='messaging.messagingproviderconnection')),
            ],
        ),
        migrations.CreateModel(
            name='MessageCommandReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('resulting_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_command_receipts', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='messaging.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_command_receipts', to='organizations.organization')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='messaging.messagedeliveryattempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'operation', 'idempotency_key'), name='messaging_command_idempotency_unique')],
            },
        ),
        migrations.CreateModel(
            name='MessageStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pendente'), ('queued', 'Na fila'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('uncertain', 'Incerto')], max_length=20)),
                ('command_id', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=60)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_status_changes', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='messaging.message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_status_history', to='organizations.organization')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('message', 'command_id'), name='messaging_history_command_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'semantic_key', 'version'), name='messaging_template_semantic_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ('whatsapp', 'email'))), name='messaging_template_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='messaging_template_version_positive'),
        ),
        migrations.AddIndex(
            model_name='messagedeliveryattempt',
            index=models.Index(fields=['organization', 'message'], name='msg_attempt_org_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagedeliveryattempt',
            constraint=models.UniqueConstraint(fields=('message', 'dispatch_key'), name='messaging_attempt_dispatch_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='messagedeliveryattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id', ''), _negated=True), fields=('channel', 'external_message_id'), name='messaging_attempt_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='messagedeliveryattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('requested', 'sending', 'accepted', 'uncertain'))), fields=('message',), name='messaging_attempt_one_active'),
        ),
        migrations.AddConstraint(
            model_name='messagedeliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('requested', 'sending', 'accepted', 'delivered', 'failed', 'cancelled', 'uncertain'))), name='messaging_attempt_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagedeliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='messaging_attempt_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='messagedeliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dispatch_lease_expires_at__isnull', True), ('dispatch_lease_token__isnull', True)), models.Q(('dispatch_lease_expires_at__isnull', False), ('dispatch_lease_token__isnull', False)), _connector='OR'), name='messaging_attempt_lease_complete'),
        ),
        migrations.AddConstraint(
            model_name='messageautomationrule',
            constraint=models.UniqueConstraint(fields=('organization', 'event_type', 'template', 'channel'), name='messaging_rule_event_template_channel_unique'),
        ),
        migrations.AddConstraint(
            model_name='messageautomationrule',
            constraint=models.CheckConstraint(condition=models.Q(('event_version__gte', 1)), name='messaging_rule_event_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='messageautomationrule',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='messaging_rule_version_positive'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='msg_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization', 'source_type', 'source_id'], name='msg_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'queued', 'sending', 'sent', 'delivered', 'failed', 'cancelled', 'uncertain'))), name='messaging_message_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ('order', 'fulfillment', 'payment'))), name='messaging_message_source_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('channel_kind__in', ('whatsapp', 'email'))), name='messaging_message_channel_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='messaging_message_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('template_version__gte', 1)), name='messaging_message_template_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('source_version__gte', 1)), name='messaging_message_source_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', False), ('status', 'sent')), models.Q(('status', 'sent'), _negated=True), _connector='OR'), name='messaging_message_sent_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivered_at__isnull', False), ('status', 'delivered')), models.Q(('status', 'delivered'), _negated=True), _connector='OR'), name='messaging_message_delivered_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('failed_at__isnull', False), ('status', 'failed')), models.Q(('status', 'failed'), _negated=True), _connector='OR'), name='messaging_message_failed_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('status', 'cancelled')), models.Q(('status', 'cancelled'), _negated=True), _connector='OR'), name='messaging_message_cancelled_timestamp'),
        ),
        migrations.AddIndex(
            model_name='messagingpreference',
            index=models.Index(fields=['organization', 'contact_point', 'channel', 'purpose'], name='messaging_pref_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagingpreference',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ('whatsapp', 'email'))), name='messaging_preference_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagingpreference',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ('allowed', 'suppressed'))), name='messaging_preference_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagingpreference',
            constraint=models.CheckConstraint(condition=models.Q(('policy_version__gte', 1)), name='messaging_preference_policy_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='messagingproviderconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'display_name'), name='messaging_connection_org_provider_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='messagingproviderconnection',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ('evolution', 'whatsapp_cloud', 'ses'))), name='messaging_connection_provider_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagingproviderconnection',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ('linked_device', 'official', 'email'))), name='messaging_connection_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagingproviderconnection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'linked_device'), ('provider', 'evolution')), models.Q(('mode', 'official'), ('provider', 'whatsapp_cloud')), models.Q(('mode', 'email'), ('provider', 'ses')), _connector='OR'), name='messaging_connection_provider_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagingproviderconnection',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='messaging_connection_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='messagingchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('external_channel_id', ''), _negated=True), fields=('connection', 'external_channel_id'), name='messaging_channel_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='messagingchannel',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('whatsapp', 'email'))), name='messaging_channel_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagingchannel',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('inactive', 'connecting', 'pairing_required', 'active', 'degraded', 'disconnected', 'disabled'))), name='messaging_channel_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagingchannel',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='messaging_channel_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='messagewebhookreceipt',
            constraint=models.UniqueConstraint(fields=('channel', 'external_message_id', 'authenticated_request_id_digest'), name='messaging_webhook_replay_unique'),
        ),
    ]
