# Generated for Vidalys Flow Phase 07.
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("organizations", "0001_initial")]
    operations = [
        migrations.CreateModel(name="IntegrationConnection", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("key", models.SlugField(max_length=100)), ("adapter_key", models.SlugField(default="reference", max_length=100)), ("status", models.CharField(choices=[("inactive", "Inactive"), ("active", "Active"), ("degraded", "Degraded"), ("disabled", "Disabled")], default="inactive", max_length=16)), ("secret_alias", models.CharField(blank=True, max_length=160)), ("config", models.JSONField(blank=True, default=dict)), ("failure_count", models.PositiveIntegerField(default=0)), ("last_success_at", models.DateTimeField(blank=True, null=True)), ("degraded_at", models.DateTimeField(blank=True, null=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="integration_connections", to="organizations.organization"))], options={"constraints": [models.UniqueConstraint(fields=("organization", "key"), name="integrations_connection_key_org_uniq")]}),
        migrations.CreateModel(name="IntegrationEndpoint", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("key", models.SlugField(max_length=100)), ("direction", models.CharField(choices=[("ingress", "Ingress"), ("egress", "Egress")], max_length=8)), ("contract_version", models.PositiveIntegerField(default=1)), ("is_active", models.BooleanField(default=False)), ("config", models.JSONField(blank=True, default=dict)), ("connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="endpoints", to="integrations.integrationconnection")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="integration_endpoints", to="organizations.organization"))], options={"constraints": [models.UniqueConstraint(fields=("connection", "key", "contract_version"), name="integrations_endpoint_version_uniq")]}),
        migrations.CreateModel(name="IntegrationDelivery", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("source_type", models.CharField(max_length=120)), ("source_id", models.CharField(max_length=120)), ("source_version", models.PositiveIntegerField()), ("contract_version", models.PositiveIntegerField()), ("operation_key", models.CharField(max_length=120)), ("idempotency_key", models.CharField(max_length=160)), ("payload_digest", models.CharField(max_length=64)), ("payload", models.JSONField(default=dict)), ("status", models.CharField(choices=[("pending", "Pending"), ("queued", "Queued"), ("sending", "Sending"), ("accepted", "Accepted"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("uncertain", "Uncertain"), ("cancelled", "Cancelled")], default="pending", max_length=16)), ("next_attempt_at", models.DateTimeField(blank=True, null=True)), ("connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deliveries", to="integrations.integrationconnection")), ("endpoint", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deliveries", to="integrations.integrationendpoint")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="integration_deliveries", to="organizations.organization"))], options={"constraints": [models.UniqueConstraint(fields=("organization", "idempotency_key"), name="integrations_delivery_idem_org_uniq"), models.UniqueConstraint(fields=("endpoint", "source_type", "source_id", "source_version", "operation_key", "contract_version"), name="integrations_delivery_source_uniq")]}),
        migrations.CreateModel(name="IntegrationDeliveryAttempt", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("sequence", models.PositiveIntegerField()), ("status", models.CharField(choices=[("requested", "Requested"), ("sending", "Sending"), ("accepted", "Accepted"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("uncertain", "Uncertain"), ("cancelled", "Cancelled")], default="requested", max_length=16)), ("lease_token", models.CharField(blank=True, max_length=64)), ("lease_expires_at", models.DateTimeField(blank=True, null=True)), ("external_id", models.CharField(blank=True, max_length=160)), ("result_code", models.CharField(blank=True, max_length=80)), ("retryable", models.BooleanField(default=False)), ("delivery", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attempts", to="integrations.integrationdelivery")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="integration_delivery_attempts", to="organizations.organization"))], options={"constraints": [models.UniqueConstraint(fields=("delivery", "sequence"), name="integrations_attempt_sequence_uniq"), models.UniqueConstraint(condition=models.Q(("status__in", ("requested", "sending", "accepted", "uncertain"))), fields=("delivery",), name="integrations_attempt_one_active")]}),
        migrations.CreateModel(name="IntegrationWebhookReceipt", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("external_event_id", models.CharField(max_length=160)), ("contract_version", models.PositiveIntegerField()), ("payload_digest", models.CharField(max_length=64)), ("disposition", models.CharField(max_length=40)), ("occurred_at", models.DateTimeField(blank=True, null=True)), ("connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="webhook_receipts", to="integrations.integrationconnection")), ("endpoint", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="webhook_receipts", to="integrations.integrationendpoint")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="integration_webhook_receipts", to="organizations.organization"))], options={"constraints": [models.UniqueConstraint(fields=("connection", "endpoint", "external_event_id"), name="integrations_webhook_event_uniq")]}),
        migrations.CreateModel(name="IntegrationReconciliationRun", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("subject_key", models.CharField(max_length=160)), ("cursor", models.CharField(blank=True, max_length=160)), ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("uncertain", "Uncertain")], default="pending", max_length=16)), ("result_code", models.CharField(blank=True, max_length=80)), ("connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reconciliations", to="integrations.integrationconnection")), ("delivery", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reconciliations", to="integrations.integrationdelivery")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="integration_reconciliations", to="organizations.organization"))], options={"constraints": [models.UniqueConstraint(fields=("organization", "connection", "subject_key", "cursor"), name="integrations_reconcile_idem_uniq")]}),
    ]
