# Generated by Django 5.2.16 on 2026-07-29 01:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=160)),
                ('aggregate_type', models.CharField(max_length=120)),
                ('aggregate_id', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('retry', 'Nova tentativa'), ('processed', 'Processado'), ('dead', 'Morto')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='organizations.organization')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'available_at'], name='outbox_pending_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='outbox_idempotency_unique_per_organization')],
            },
        ),
    ]
