# Generated by Django 5.2 on 2026-08-15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataImportBatchReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[("customers", "Clientes"), ("products", "Produtos")],
                        max_length=32,
                    ),
                ),
                ("source_digest", models.CharField(max_length=64)),
                ("row_count", models.PositiveIntegerField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_import_batches",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "domain", "source_digest"),
                        name="data_import_batch_unique_per_org_domain",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataImportRowReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                ("row_digest", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=120)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="platform.dataimportbatchreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ("row_number",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"),
                        name="data_import_row_unique_per_batch",
                    )
                ],
            },
        ),
    ]
