# Generated by Django 5.2.16 on 2026-08-09 01:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('pagarme', 'Pagar.me')], max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('active', 'Ativo'), ('processing', 'Processando'), ('paid', 'Pago'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='requested', max_length=20)),
                ('provider_idempotency_key', models.CharField(max_length=64)),
                ('external_resource_id', models.CharField(blank=True, max_length=160)),
                ('hosted_url', models.URLField(blank=True, max_length=1000)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='organizations.organization')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting_payment', 'Aguardando pagamento'), ('processing', 'Processando'), ('paid', 'Pago'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('requires_attention', 'Requer atenção')], default='pending', max_length=30)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_number_snapshot', models.CharField(max_length=20)),
                ('customer_name_snapshot', models.CharField(max_length=200)),
                ('snapshot_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('attention_code', models.CharField(blank=True, max_length=60)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intent', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentCommandReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('resulting_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_command_receipts', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='payments.paymentattempt')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_command_receipts', to='organizations.organization')),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='payments.paymentintent')),
            ],
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='payments.paymentintent'),
        ),
        migrations.CreateModel(
            name='PaymentProviderAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('pagarme', 'Pagar.me')], max_length=30)),
                ('display_name', models.CharField(max_length=120)),
                ('credential_alias', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('callbacks_enabled', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_provider_accounts', to='organizations.organization')),
            ],
            options={
                'ordering': ('provider', 'display_name'),
            },
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='provider_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='payments.paymentprovideraccount'),
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting_payment', 'Aguardando pagamento'), ('processing', 'Processando'), ('paid', 'Pago'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('requires_attention', 'Requer atenção')], max_length=30)),
                ('command_id', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=60)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='payments.paymentintent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_status_history', to='organizations.organization')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('pagarme', 'Pagar.me')], max_length=30)),
                ('external_event_id', models.CharField(max_length=160)),
                ('external_resource_id', models.CharField(max_length=160)),
                ('request_digest', models.CharField(max_length=64)),
                ('canonical_result', models.CharField(max_length=30)),
                ('accepted', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_webhook_receipts', to='organizations.organization')),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_receipts', to='payments.paymentprovideraccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='payment_intent_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'awaiting_payment', 'processing', 'paid', 'cancelled', 'expired', 'requires_attention'))), name='payment_intent_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'BRL')), name='payment_intent_currency_brl'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_intent_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='payment_intent_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_at__isnull', False), ('status', 'paid')), models.Q(('status', 'paid'), _negated=True), _connector='OR'), name='payment_intent_paid_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'requires_attention'), models.Q(('attention_code', ''), _negated=True)), models.Q(models.Q(('status', 'requires_attention'), _negated=True), ('attention_code', '')), _connector='OR'), name='payment_intent_attention_code'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('status', 'cancelled')), models.Q(('status', 'cancelled'), _negated=True), _connector='OR'), name='payment_intent_cancel_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expired_at__isnull', False), ('status', 'expired')), models.Q(('status', 'expired'), _negated=True), _connector='OR'), name='payment_intent_expired_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='paymentcommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'operation', 'idempotency_key'), name='payment_command_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentprovideraccount',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'display_name'), name='payment_account_org_provider_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentprovideraccount',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ('mercado_pago', 'pagarme'))), name='payment_account_provider_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentprovideraccount',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='payment_account_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentprovideraccount',
            constraint=models.CheckConstraint(condition=models.Q(('provider', 'mercado_pago'), ('callbacks_enabled', False), _connector='OR'), name='payment_pagarme_callback_disabled'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['organization', 'intent'], name='payment_attempt_org_intent_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('intent', 'provider_idempotency_key'), name='payment_attempt_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('external_resource_id', ''), _negated=True), fields=('provider_account', 'external_resource_id'), name='payment_attempt_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('requested', 'active', 'processing'))), fields=('intent',), name='payment_attempt_one_active'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('requested', 'active', 'processing', 'paid', 'failed', 'cancelled', 'expired'))), name='payment_attempt_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='payment_attempt_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_resource_id', ''), ('hosted_url', ''), ('status', 'requested')), models.Q(('status', 'requested'), _negated=True), _connector='OR'), name='payment_attempt_requested_empty'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), models.Q(('external_resource_id', ''), _negated=True), models.Q(('hosted_url', ''), _negated=True)), models.Q(('status', 'active'), _negated=True), _connector='OR'), name='payment_attempt_active_complete'),
        ),
        migrations.AddConstraint(
            model_name='paymentstatushistory',
            constraint=models.UniqueConstraint(fields=('intent', 'command_id'), name='payment_history_command_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookreceipt',
            constraint=models.UniqueConstraint(fields=('provider_account', 'external_event_id'), name='payment_webhook_event_unique'),
        ),
    ]
