PAYMENT_INTENT_CREATED = "payment.intent_created"
PAYMENT_CHECKOUT_REQUESTED = "payment.checkout_requested"
PAYMENT_CHECKOUT_ACTIVATED = "payment.checkout_activated"
PAYMENT_STATUS_CHANGED = "payment.status_changed"
PAYMENT_REQUIRES_ATTENTION = "payment.requires_attention"
PAYMENT_CANCELLED = "payment.cancelled"
