# Generated by Django on 2026-08-08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fulfillment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("method", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20, default="draft")),
                ("destination_snapshot", models.JSONField(default=dict, blank=True)),
                ("snapshot_schema_version", models.PositiveSmallIntegerField(default=1)),
                ("pickup_unit_name_snapshot", models.CharField(blank=True, max_length=200)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("preparing_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=500)),
                ("system_cancelled", models.BooleanField(default=False)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fulfillments_created", to=settings.AUTH_USER_MODEL)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fulfillments", to="orders.order")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fulfillments", to="organizations.organization")),
                ("pickup_unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="fulfillments", to="organizations.organizationunit")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FulfillmentItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("fulfillment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="fulfillment.fulfillment")),
                ("order_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fulfillment_items", to="orders.orderitem")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fulfillment_items", to="organizations.organization")),
            ],
            options={
                "ordering": ("order_item__position",),
            },
        ),
        migrations.CreateModel(
            name="FulfillmentStatusHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("command_id", models.CharField(max_length=64)),
                ("reason_provided", models.BooleanField(default=False)),
                ("system_generated", models.BooleanField(default=False)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fulfillment_status_changes", to=settings.AUTH_USER_MODEL)),
                ("fulfillment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="status_history", to="fulfillment.fulfillment")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fulfillment_status_history", to="organizations.organization")),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="FulfillmentCommandReceipt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation", models.CharField(max_length=80)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("resulting_version", models.PositiveBigIntegerField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="fulfillment_command_receipts", to=settings.AUTH_USER_MODEL)),
                ("fulfillment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="command_receipts", to="fulfillment.fulfillment")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fulfillment_command_receipts", to="organizations.organization")),
            ],
        ),
    ]
