# Generated by Django 5.2.16 on 2026-08-08 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('delivery', 'Entrega'), ('pickup', 'Retirada')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('preparing', 'Em separação'), ('ready', 'Pronto'), ('in_transit', 'Em trânsito'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('destination_snapshot', models.JSONField(blank=True, default=dict)),
                ('snapshot_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('pickup_unit_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=500)),
                ('system_cancelled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='organizations.organization')),
                ('pickup_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='organizations.organizationunit')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FulfillmentCommandReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('source_event_id', models.UUIDField(blank=True, null=True)),
                ('resulting_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_command_receipts', to=settings.AUTH_USER_MODEL)),
                ('fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='fulfillment.fulfillment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_command_receipts', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FulfillmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='fulfillment.fulfillment')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_items', to='orders.orderitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_items', to='organizations.organization')),
            ],
            options={
                'ordering': ('order_item__position',),
            },
        ),
        migrations.CreateModel(
            name='FulfillmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Rascunho'), ('preparing', 'Em separação'), ('ready', 'Pronto'), ('in_transit', 'Em trânsito'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], max_length=20)),
                ('command_id', models.CharField(max_length=64)),
                ('reason_provided', models.BooleanField(default=False)),
                ('system_generated', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='fulfillment.fulfillment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_status_history', to='organizations.organization')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='fulfillment_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillment',
            index=models.Index(fields=['organization', 'order'], name='fulfillment_org_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='fulfillment',
            constraint=models.UniqueConstraint(fields=('order', 'sequence'), name='fulfillment_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='fulfillment',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='fulfillment_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='fulfillment',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='fulfillment_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='fulfillment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ('delivery', 'pickup'))), name='fulfillment_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='fulfillment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'preparing', 'ready', 'in_transit', 'completed', 'cancelled'))), name='fulfillment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='fulfillment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'delivery'), ('pickup_unit__isnull', True), ('pickup_unit_name_snapshot', '')), models.Q(('destination_snapshot', {}), ('method', 'pickup'), ('pickup_unit__isnull', False), models.Q(('pickup_unit_name_snapshot', ''), _negated=True)), _connector='OR'), name='fulfillment_method_snapshot_consistent'),
        ),
        migrations.AddConstraint(
            model_name='fulfillment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('cancelled_at__isnull', True), ('status', 'cancelled'), _negated=True), models.Q(('cancel_reason', ''), ('status', 'cancelled'), _negated=True)), models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancel_reason', ''), ('cancelled_at__isnull', True), ('system_cancelled', False)), _connector='OR'), name='fulfillment_cancel_metadata'),
        ),
        migrations.AddIndex(
            model_name='fulfillmentcommandreceipt',
            index=models.Index(fields=['organization', 'fulfillment'], name='fulfillment_receipt_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentcommandreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'operation', 'idempotency_key'), name='fulfillment_command_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='fulfillmentitem',
            index=models.Index(fields=['organization', 'order_item'], name='fulfillment_item_org_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentitem',
            constraint=models.UniqueConstraint(fields=('fulfillment', 'order_item'), name='fulfillment_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='fulfillment_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentstatushistory',
            constraint=models.UniqueConstraint(fields=('fulfillment', 'to_status'), name='fulfillment_history_status_unique'),
        ),
    ]
