# Generated by Django 5.2.16 on 2026-08-08 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fulfillmentstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status__in', ('', 'draft', 'preparing', 'ready', 'in_transit', 'completed', 'cancelled'))), name='fulfillment_history_from_valid'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ('draft', 'preparing', 'ready', 'in_transit', 'completed', 'cancelled'))), name='fulfillment_history_to_valid'),
        ),
    ]
