# Generated by Django 5.2.16 on 2026-07-29 01:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('entity_type', models.CharField(max_length=120)),
                ('entity_id', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
